name: Sample

on:
  push:
    branches:
      - kita127-patch-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install -g typescript
      - name: Compile TypeScript
        run: tsc autoUpload.ts
      - name: Run auto upload script
        run: node autoUpload.js
